### PR TITLE
Add more Magic types to support more MOD files

### PR DESCRIPTION
**Pull request by DevanWolf**
The player is missing some/most MOD magic signatures (like 2 channels for example) which makes the player unable to load without them being supported. That is why I have added support for MOD files of channels 1-999 and included some other formats like CDx1 made from Octalyser, NSMS from kingdomofpleasure.mod, etc.
Sorry for FLT8 taken away because 8 channel MOD files made in Startrekker are completely different than Octalyser/FT2's 8 channel system.

### CODE REVIEW

**Comment by jfdelnero** [comment]
Thanks. I think i will try to avoid to embed all these strings and do it programmatically. 
Have you tested some of these mods with your patched HxCModPlayer ?

**Comment by DevanWolf** [comment]
I tested a 120 channel MOD I made and seems to crash the Windows player.
[120Ch.zip](https://github.com/jfdelnero/HxCModPlayer/files/3239110/120Ch.zip)
Possibly fixable?

**Comment by jfdelnero** [comment]
You probably need to change the NUMMAXCHANNELS define from 32 to 128 in the hxcmod.h file.

**Comment by DevanWolf** [comment]
Okay, fixed now! Now accept my pull request and recompile the Windows program with my patched!

**Comment by jfdelnero** [comment]
I made another implementation to suppress most of these signature strings from the binary. The windows software and web page are now updated.
Thanks for providing me these signatures !

**Comment by jfdelnero** [comment]
The new magic types support is now implemented. Closing.

**Comment by DevanWolf** [comment]
Hey, you could've left FLT4 and EXO4 alone, but if you load an FLT8 mod to this player (e.g. gidion graveland.mod) it will sound messed up, while OpenMPT sounded fine.

**Comment by jfdelnero** [comment]
gidion graveland.mod ? Are you sure ? This one appears to work fine and isn't a FLT8, at least with the ones i found on internet. Can you share your particular version ?

**Comment by DevanWolf** [comment]
> gidion graveland.mod ? Are you sure ? This one appears to work fine and isn't a FLT8, at least with the ones i found on internet. Can you share your particular version ?

Did you mean [this one](http://modland.com/pub/modules/Startrekker%20FLT8/-%20unknown/gidion%20graveland.mod)?

**Pull request closed without merging**
